server:
  port: 3003
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/spring_backend
    driver-class-name: org.mariadb.jdbc.Driver
    username: sbAdmin
    password: gksfla1008

mybatis:
 mapper-locations: classpath:mapper/**/*.xml
 type-aliases-package: com.dictation.vo