server:
  port: 3003
spring:
  datasource:
    url: jdbc:mariadb://localhost:3333/mydb?useUnicode=true&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 25802580

mybatis:
 mapper-locations: classpath:mapper/**/*.xml
 type-aliases-package: com.dictation.vo

#추가 (쓰면 칼럼명에 언더바 못알아봄)
# configuration:
#   map-underscore-to-camel-case: true